name: cmustify
version: 0.0.1
author: Kim Desrosiers <kimdesro@gmail.com>
homepage: https://github.com/Pacane/cmustify
description: A cmus utility that show notifications with the current playing song information.
executables:
  cmustify:
dependencies:
  test: '>=0.12.13+4 <0.13.0'
